### PR TITLE
move templates documentation to groovy-templates subproject

### PR DESCRIPTION
**Pull request by PascalSchumacher**
Locally I get this test failure (test is unrelated to changes):

groovy.text.StreamingTemplateEngineSpecification > should execute the javadoc example same as GStringTemplateEngine FAILED
    groovy.lang.MissingMethodException: No signature of method: groovy.text.StreamingTemplateEngineSpecification.template() is applicable for argument
 types: (java.lang.Class, java.lang.String, java.util.LinkedHashMap) values: [class groovy.lang.GString, Dear <% out.print firstname %> ${lastname},

    We <% if (accepted) out.print 'are pleased' else out.print 'regret' %> to inform you that your paper entitled
    '$title' was ${ accepted ? 'accepted' : 'rejected' }.

    The conference committee.
            , ...]
        at groovy.text.StreamingTemplateEngineSpecification.should execute the javadoc example same as GStringTemplateEngine(StreamingTemplateEngineSpecification.groovy:248)

@paulk-asert : Just a vague guess, but maybe this is somehow related to  GROOVY-7346 MissingMethodException: No signature of method: com.sun.org.apache.xerces.internal.dom.DeferredElementNSImpl.xpath()

### CODE REVIEW

**Comment by melix** [comment]
So the test doesn't fail on the CI server. Everything seem to indicate that the issue you are facing is directly related to Windows.

**Comment by paulk-asert** [comment]
@Pascal, yep, it looks like the same symptoms:
`groovy.text.StreamingTemplateEngineSpecification.EngineType.GSTRING => Class<groovy.lang.GString>`
`javax.xml.namespace.QName.XPathConstants.NODE => Class<groovy.util.Node>`
I imagine there is some implicit assumption in PR#552 that windows case-insensitive file system is breaking. I would regard it as a blocker for the 2.5 release myself.

**Comment by melix** [comment]
See my comment on #552.

**Comment by PascalSchumacher** [comment]
This now works on Windows. Thanks! :)

I will backport the change to 2.4.X.

**Pull request merged**
