### PR TITLE
An ability to resolve references using ASM, without classloading

### PR DESCRIPTION
**Pull request by donnerpeter**
ClassNodeResolver now has two optimization options, both true by default: asmResolving to enable resolving with ASM (see AsmDecompiler class), and classLoaderResolving to enable the old, classloader-based resolution. Command-line compilers are supposed to turn the latter off.

I haven't observed significant difference in running times for tests or building groovy-core, but compiling against this jar in IntelliJ definitely gives some speedup. I'm not even sure that ASM resolving should be on by default, but as I haven't observed slowdowns on my Linux, I turned it on. Testing on other OSes might be helpful.

A couple unresolved questions:
* Java5 treatment of ParameterizedType is incorrect: it doesn't take into account getOwnerType(). I've made ASM decompiler behave the same way for now. I don't know how to represent such types in ClassNode API.
* Java5#configureClassNode has some logic concerning package annotations. I strongly suspect that it never works because compiled classes don't have modules (and hence packages). I couldn't find how to make this code work, so I didn't reflect the same logic in ASM decompiler.
* I've added only unit tests. Maybe, tests involving full-blown command-line compilation could also be useful, but I haven't found examples of those yet.

Possible improvements:
* Lazy MethodNode parameters and return type parsing
* Caching ClassStub. One should be careful to avoid false positives when different same-named classes are used.

BTW: how about creating a class/interface with all available optimization options as constants?

### CODE REVIEW

**Comment by PascalSchumacher** [comment]
Jira issue for this enhancement is https://jira.codehaus.org/browse/GROOVY-4024

**Comment by paulk-asert** [comment]
Peter, there might be some issues with the PR on Windows that we hadn't noticed before. See the comments on PR#641 and https://jira.codehaus.org/browse/GROOVY-7346. Or it could be unrelated and we are missing something else altogether. If there is an issue, do you have any thoughts on where we might start looking? Thanks.

**Comment by melix** [comment]
I have pushed a workaround for that problem: https://github.com/groovy/groovy-core/commit/1a0969697cc311af1902cc2489a7b80f56a6e878

Basically, the problem is that ClassLoader#getResource is case insensitive under Windows (and probably on any jar found on on a case insensitive FS but I couldn't reproduce). So `groovy/util/NODE.class` matched on `groovy/util/Node.class`, which is rather unfortunate. I couldn't find any way to make `getResource` case sensitive, if any of you has a better idea.. /cc @PascalSchumacher

**Comment by donnerpeter** [comment]
@melix @paulk-asert Thanks for looking into this issue! I wasn't aware of this getResource behavior, sorry. As it turns out, ClassLoader does the same: defineClass also checks if the name in class file equals the name being searched for. So the fix looks right for me.

**Comment by melix** [comment]
Excellent, thank you Peter!

**Pull request merged**
