### PR TITLE
Add a possibility to invoke private classes of inner/outer classes. GROO...

### PR DESCRIPTION
**Pull request by xSeagullx**
...VY-6468.
[JIRA](http://jira.codehaus.org/browse/GROOVY-6468)

Should I test recursive cases, or inheritance case.

### CODE REVIEW

**Comment by xSeagullx** [comment]
Dear @melix

Is it ok, that I have touched JIRA already assigned to you? I haven't seen any branch/open pull-request from you about that ticket.

**Comment by melix** [comment]
Excellent @xSeagullx ! Not the easiest part of Groovy that you are looking at :)

I will review this, no problem that you take a look at it. I'd like to check the bytecode which is generated too, to make sure it doesn't contain any dynamic invocation in that case.

**Comment by xSeagullx** [comment]
@melix I'm sure, that my unit test are bad, because now they just show us that no compiler error is raised. I've changed them to do an actual constructor invocation.

```
//Added this (for outer)
assert new Foo.Bar().foo() instanceof Foo
// And this (for inner)
assert new Foo().foo() instanceof Foo.Bar
```

And now outer class test failed with ```tried to access method Foo.<init>()V from class Foo$Bar
java.lang.IllegalAccessError: tried to access method Foo.<init>()V from class Foo$Bar```

I'll check it this evening, after work.

__P.S.__ I see no easy way to look into bytecode. If you have a secret knowledge(probably i can turn on some logger or smth like that) please share it =)

**Comment by blackdrag** [comment]
looking at the bytecode can be done for example using javap. I often use Textifier/CheckClassAdapater/ASMifierClassVisitor from the asm lib.

**Comment by melix** [comment]
Another option is to use the `astTrees` property that the StaticCompilationTestSupport class provides (see for example https://github.com/melix/groovy-core/blob/master/src/test/org/codehaus/groovy/classgen/asm/sc/bugs/Groovy6962Bug.groovy#L22-22) or use the AbstractByteCodeTestCase (like https://github.com/melix/groovy-core/blob/master/src/test/org/codehaus/groovy/classgen/asm/sc/StaticCompilationTest.groovy)

**Comment by xSeagullx** [comment]
@melix It seems I've done very naive attempt to fix it =)
Should investigate deeper. As far as I can see, __both__ cases doesn't introduce virtual calls. But bytecode for calling `<init>` method is wrong, so why I get `IllegalAccessError`.

I can return to this issue on Sunday, but I can't guarantee that I'll be able to solve it quickly. Especially, because debagging that stuff is really hard.

__Below is just working thoughts, but I'd be happy if you point out possible mistake or suggest a place to look__
AFAIU, there should be 2 arg init method call in private constructor test(as it's not static)
Smth like
```
    NEW Foo$Bar
    DUP
    ALOAD 0
    ACONST_NULL
    INVOKESPECIAL Foo$Bar.<init> (LFoo;LFoo$1;)V
    ARETURN
```
And I get `Foo$Bar.<init>(LFoo;)V` in exception message, which is obviously wrong.

So, I need to:
   Verify that `Foo$Bar.<init> (LFoo;LFoo$1;)V` is created.
   Find a place where invokation bytecode is generated. Tweek it for inner/outer classes support.

**Comment by melix** [comment]
I think there should be a way for you not to directly generate bytecode for this but rely on existing code. I would suggest debugging what path is taken in AsmClassGenerator without CompileStatic for this, and see if we cannot reuse some code. Be careful that I am not saying that it is doable, it's only how I would start.

**Pull request closed without merging**
