### PR TITLE
fix some typos

### PR DESCRIPTION
**Pull request by JBrownVisualSpection**
Also a quick question, how often is the documentation site refreshed? I've found other on the site that were already fixed in master.

### CODE REVIEW

**Comment by PascalSchumacher** [comment]
@melix: How often is the documentation site refreshed?

**Comment by PascalSchumacher** [comment]
Merged. Thanks!

**Comment by PascalSchumacher** [comment]
@JBrownVisualSpection I'm not sure, but I believe the documentation of the site http://beta.groovy-lang.org/single-page-documentation.html is only refreshed if a new groovy version is published.

**Comment by melix** [comment]
The documentation for pages like http://groovy-lang.org/differences.html is updated when the web site refreshes but they link to or integrate with the latest *released* documentation. For upcoming documentation there's a special symlink: http://docs.groovy-lang.org/latest/html/documentation/

**Pull request merged**
