### PR TITLE
relativePath default groovy method

### PR DESCRIPTION
**Pull request by bsideup**
Simple but useful method inspired by GFileUtils from Gradle build system ( https://github.com/gradle/gradle/blob/5f98c7d9e52033d9eb32b635d7edc60319a363ba/subprojects/core/src/main/groovy/org/gradle/util/GFileUtils.java#L236 )

### CODE REVIEW

**Comment by bsideup** [comment]
Um... Er..... similarly to another methods :D Should I remove it at all?

**Comment by bsideup** [comment]
Pushed new version without deprecated method (+ with tests)

**Comment by bsideup** [comment]
New version without Ant dependency (Implementation was borrowed from Ant's FileUtils since it's pretty good and clean)

**Comment by melix** [comment]
+1

**Comment by melix** [comment]
Is there a releated JIRA ticket? (Useful for release notes)

**Comment by bsideup** [comment]
Nope. I can create one if you want

**Comment by melix** [comment]
Sure, thank you!

**Comment by bsideup** [comment]
https://jira.codehaus.org/browse/GROOVY-7313

done

**Pull request merged**
