### PR TITLE
Create a Java version of Cedric Champeau's FileTreeBuilder which allows ...

### PR DESCRIPTION
**Pull request by sbuettner**
...File objects to access it via ResourceGroovyMethods.

as discussed on Twitter: https://twitter.com/CedricChampeau/status/573093312472748033

### CODE REVIEW

**Comment by melix** [comment]
Thanks! I'm a bit sad to see a Groovy file converted to Java for build reasons, let me see if I can find a workaround.

**Comment by melix** [comment]
Follow-up: we are investigating how to add groovy methods added in groovy core itself. We already have a solution for this, and it would allow not to convert the class into Java. I will let you know.

**Comment by sbuettner** [comment]
Great, although i could live with a Java version since most util classes are also java. :relieved:

**Comment by melix** [comment]
I understand it's no problem for you but it is for us, because we'd like to have more code written in Groovy itself :)

**Comment by sbuettner** [comment]
All good. Happy when it is there (groovy or not) and ready to use it for tests and other areas.

**Comment by PascalSchumacher** [comment]
@melix What about merging this if @sbuettner rebases it to current master?

**Comment by melix** [comment]
I'm not too fond of rewriting this in Java so far. I think the feature is good as is right now and can be added as a DGM method later once we find a better solution.

**Comment by sbuettner** [comment]
I would look into rebasing this if you want to.

**Comment by sbuettner** [comment]
Just curious, whats the resolution of this PR?

**Comment by PascalSchumacher** [comment]
@sbuettner Sorry to see your work wasted, but Cédric did not agree to merge this, so I did not merge.

**Pull request closed without merging**
