### PR TITLE
GROOVY-7344: Disallow numbers with multiple decimal points from being parsed incorrectly.

### PR DESCRIPTION
**Pull request by ataylor284**
Prevents groovy from incorrectly parsing JSON numbers like e.g. 1.1.1 as 1.11.

### CODE REVIEW

**Comment by melix** [comment]
Excellent, thanks!

**Comment by PascalSchumacher** [comment]
@ataylor284  seems like your change broke the JsonSlurperIndexOverlayTest.testNullEmptyMalformedPayloads test see: http://ci.groovy-lang.org/viewLog.html?buildId=15302&tab=buildResultsDiv&buildTypeId=Groovy_Jdk7Build

**Comment by ataylor284** [comment]
@PascalSchumacher sorry about the test failure.  I've updated the parser and created a new pull request here: https://github.com/groovy/groovy-core/pull/639

**Comment by PascalSchumacher** [comment]
@ataylor284  np Thanks for the fix. :)

**Pull request merged**
