### PR TITLE
GROOVY-7353: Groovy should provide a MapConstructor AST transform (initi...

### PR DESCRIPTION
**Pull request by paulk-asert**
...al commit)

### CODE REVIEW

**Comment by bsideup** [comment]
How it will co-exist with http://docs.groovy-lang.org/latest/html/documentation/#_named_argument_constructor ?

**Comment by paulk-asert** [comment]
Groovy's named arguments for constructors work when either a Map constructor is present or a no-arg constructor (the default) plus setters. So, to answer your question, you should notice no change.

**Comment by bsideup** [comment]
@paulk-asert ok, cool:)

**Comment by paulk-asert** [comment]
Moved to apache repo.

**Pull request closed without merging**
