### PR TITLE
Groovy macro

### PR DESCRIPTION
**Pull request by melix**
This PR supercedes #470 : it is the same contents but rebased onto master. See #470 for discussion. I think we should merge this, even if there is still discussion about the global transform, ASTMatcher being incomplete and no nice API to help with AST transformations (ASTMatcher is a beginning).

Also, we miss documentation, but the move to Apache makes it easier to merge it now.

### CODE REVIEW

**Comment by bsideup** [comment]
@melix nice! Just give me a day or two to perform some cleanups and little improvements since it's outdated a little.

**Comment by melix** [comment]
Right, so I assume you will send a new PR on my groovy-macro branch?

**Comment by bsideup** [comment]
Yes, it makes sense to use your branch since it's rebased

**Comment by bsideup** [comment]
Build is green. Cool, now from me there are no reasons not to merge it

**Comment by aalmiray** [comment]
I'd say we should be cautious about this feature, as you @melix said it's not fully formed. Once we put it in core it will be hard to move it out (Jigsaw save us!). I don't see the problem why this feature can continue to incubate as a groovy module extension on its own project.

**Comment by melix** [comment]
The macro stuff is pretty done. The `ASTMatcher` part still needs some work and we still need to rely on the latter to provide a better transformation API. However, the macro stuff is in its own module, and with the move to Apache, I think it would be good to merge before the repo is moved to Apache Git. BTW this is *the* major feature for 2.5.

**Comment by melix** [comment]
It would be nice to reissue a PR on https://github.com/apache/incubator-groovy. The status of this hasn't changed, but since 2.5 is still far, I don't mind having it in master and improving it. It's been too long since this PR is open, for a feature we want for 2.5.

**Comment by bsideup** [comment]
@melix Ok. Should I re-open it from your fork? (because this one comes from `melix:groovy-macro` )

**Comment by melix** [comment]
mmm, true. I thought you had made more changes since then.

**Comment by bsideup** [comment]
@melix no, your branch is the latest and greatest :)

**Comment by melix** [comment]
Ok tx. Will need some time to rebase onto master and fix the file headers with the new Apache license header.

**Comment by bsideup** [comment]
Ok :)

Ping me if you need some help with it

**Comment by PascalSchumacher** [comment]
superceded by https://github.com/groovy/groovy-core/pull/636

**Pull request closed without merging**
